<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd">
<suite parallel="tests" name="Failed suite [Suite]" guice-stage="DEVELOPMENT" verbose="0">
  <test thread-count="5" parallel="tests" name="Error Validations Test(failed)" verbose="0">
    <classes>
      <class name="Shaktiacademy.tests.ErrorValidationTest">
        <methods>
          <include name="productErrorValidation"/>
          <include name="launchApplication"/>
          <include name="loginErrorValidation"/>
          <include name="tearDown"/>
        </methods>
      </class> <!-- Shaktiacademy.tests.ErrorValidationTest -->
    </classes>
  </test> <!-- Error Validations Test(failed) -->
  <test thread-count="5" parallel="tests" name="Submit Order Test(failed)" verbose="0">
    <classes>
      <class name="Shaktiacademy.tests.SubmitOrderTest">
        <methods>
          <include name="checkorder"/>
          <include name="submitOrder"/>
          <include name="launchApplication"/>
          <include name="tearDown"/>
        </methods>
      </class> <!-- Shaktiacademy.tests.SubmitOrderTest -->
    </classes>
  </test> <!-- Submit Order Test(failed) -->
</suite> <!-- Failed suite [Suite] -->
